site_name: Solución de sistemas dinámicos con RK4

theme:
  name: "material"

nav:
  - index.md
  - explanation.md
  - tutorials.md
  - reference.md

use_directory_urls: false

plugins:
  - mkdocstrings
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math

